# This is a basic workflow to help you get started with Actions

name: TestWorkflow

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'The tag to associate to this release'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    
  upload-artifacts:
    # The type of runner that the job will run on
    runs-on: windows-latest
    

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16
          
      - name: install dependencies
        run: npm install
        
      - name: install electron-installer-windows
        run: npm install --no-save electron-installer-windows
        
      - name: Build
        run: npm run make 
      
      - name: ls contents
        run: ls out/

      - name: Create Windows Installer
        run: electron-installer-windows --src out/ctcast-win32-x64/ --dest out/installers/  
        
      - name: ls exe
        run: ls out/installers/ 

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/installers/ctcast-win32-x64.exe
          tag_name: ctcast-latest-windows
